domains/environment_domains/front_door.tf, domains/environment_domains/variables.tf
Front door resource definitions needed to be added as these were not available in previously in terraform. This commit adds the capability to deploy origin group and origin.
https://trello.com/c/AM6y1jHr
=> Add frontdoor resources

dns/records/resources.tf
Using the dns/records module we need to be able to optionally create A records.
- Add optional A record resources to dns/records module
- Make the CName record resources optional
Clone [add-platform-test-domains](https://github.com/DFE-Digital/teacher-services-cloud/tree/add-platform-test-domains) branch of teacher-services-cloud.  Run `make prod-domain domains-infra-plan`, it should report 1 DNS A record resources to add plus 1 change (tags on existing resource).
=> Add A records to dns/records module

dns/records/resources.tf, domains/environment_domains/dns.tf, domains/environment_domains/front_door.tf, domains/environment_domains/variables.tf, domains/infrastructure/variables.tf
The current module always deployed the same default TXT and CAA records for a DNS zone. It was also not possible to use it with multiple DNS zones and front doors in the same resource group.
- Move DNS related resources to the dns file.
- Add a multiple_hosted_zones boolean which can be set to true when we want the endpoint name to be more unique. Its caters for a scenario where there are two DNZ zones, front doors in the same resource group.
- Add a deploy_default_records boolean when we want to specify our own TXT and CAA records for a DNS zone.
https://trello.com/c/H6azJvT5
The following process was used to test the changes:
https://hackmd.cloudapps.digital/s/BUXSgAxV6#Testing-Process
=> 80 enhance frontdoor support

domains/environment_domains/front_door.tf, domains/environment_domains/variables.tf
If deploying multiple DNS zones, the FD endpoint name can be larger than 46 chars, 
and the terraform run will fail with error
`Error: "name" must be between 2 and 46 characters in length, begin with a letter or number, end with a letter or number and may contain only letters, numbers and hyphens, got "qa2-assets-apply-for-teacher-training-education"` 
Also add an option to override the origin host header to null, as it defaults to the same value as the host name
Create a short_zone_name variable that uses the first 3 chars of the domain after the first period
So qa2-assets-apply-for-teacher-training-education will become qa2-assets-apply-for-teacher-training-edu
Add variable null_host_header with default false.
Setting to true will set a null value for the origin_host_header
deploy-plan
=> Frontdoor fixes for apply QA

domains/environment_domains/front_door.tf, domains/environment_domains/variables.tf
The cached routes are always created since the comparison between 2 empty lists is never equal in terraform
Replace with a condition on the number of elements in the list
Run with no cached paths
=> [296] Fix for empty cached path

aks/cluster_data/README.md, aks/cluster_data/data.tf, aks/cluster_data/outputs.tf, aks/cluster_data/variables.tf
This adds a Terraform module for capturing the various AKS clusters we have configured and keeps it one place, shareable across multiple users of AKS.
Based on the notes: https://hackmd.cloudapps.digital/k9xWr1eDQ86ffMusLO2zPA
=> Add AKS Cluster Data module

.github/workflows/release.yaml
This fixes a couple of syntax errors in the YAML for the new release GitHub Action.
=> Fix YAML syntax error

.github/workflows/release.yaml
This makes two small changes to improve the release process:
- **Always update testing tag**: This ensures that even when a stable release is made, the `testing` tag is updated. Without this we can end up in situations where `stable` is more recent than `testing`.
- **Use tag name to checkout repo**: Using the target commitish doesn't quite work as it represents where the Git tag is created from. This works if the tag is new with the release, but not if we're releasing an existing tag.
=> Improve release process

aks/application/resources.tf
Update the name of the ingress so when we have more than one ingress for a service, the name can be unique based on the hostname. Otherwise the additional ingress resources failt to create because the names are the same
=> Uodate ingress name

domains/environment_domains/front_door.tf, domains/environment_domains/locals.tf, domains/environment_domains/variables.tf
Some of the domains for services are quite long (e.g. manage-training-for-early-career-teachers.education.gov.uk) and can exceed the allowed length of 46 characters when made in to the front door endpoint name. This ensures the name is never longer by removing excess characters once the name has been generated by the module.
Add a variable to define the max name size.
Use the substr function to reduce the length of the front door endpoint name if required
This shouldn't impact any existing deployments because they will all be under the 46 character length limit already.
=> 308 manage ect domain improvements

aks/application/resources.tf
This is to introduce redundancy by adding the zone and hostname constraints. 
The default value for max_skew is set to 1, the topology key is left as default values and so is the when_unsatisfiable value
=> Introduce topology contracts into the resource module

aks/application/resources.tf
Add Kubernetes Pod Distribution budget to application module. 
* Added Kubernetes Pod Distribution Budget
* Resource should only be created if the number of replicas is above 1. 
* For the time being we should stick with using 50% as the min_available replicas.
Tested with register app
Change Terrafile to reference this branch (344-terraform-modules-add-kubernetes-pod-distribution-budget-to-application-module) for version.
Change the number of replicas to above 1 for your proffered environment var file and deploy the app to see that PDB is created and 50% is set. Below 1 replicas should not create PDB.
=> Add Kubernetes pod disruption budget resource to application module

aks/postgres/resources.tf, aks/postgres/variables.tf
For the aks postgres module, we don't always want additional backups.
So make the backup resources optional, with default true.
- storage account
- container
- lifecycle policy
make using branch
=> make aks postgres backup storage account optional

aks/postgres/README.md, aks/postgres/resources.tf, aks/postgres/variables.tf, aks/redis/README.md, aks/redis/resources.tf, aks/redis/variables.tf
At the moment we use the short name for databases created in Kubernetes, which ends up with a set of deployments like this:
```
afqts-review-1445-postgres         1/1     1            1           2d22h
afqts-review-1445-redis            1/1     1            1           2d22h
afqts-review-1451-postgres         1/1     1            1           59m
afqts-review-1451-redis            1/1     1            1           59m
apply-for-qts-development-web      1/1     1            1           46m
apply-for-qts-development-worker   1/1     1            1           46m
apply-for-qts-review-1445-web      1/1     1            1           2d22h
apply-for-qts-review-1445-worker   1/1     1            1           2d22h
apply-for-qts-review-1451-web      1/1     1            1           59m …
```
=> Use full names for AKS databases

aks/postgres/README.md, aks/postgres/outputs.tf, aks/postgres/resources.tf, aks/postgres/variables.tf
This allows us to get the name of the storage account and storage container so we know where to upload backups to from GitHub Actions.
=> Add outputs for backup storage

aks/postgres/README.md, aks/postgres/data.tf, aks/postgres/resources.tf, aks/redis/README.md, aks/redis/data.tf, aks/redis/resources.tf
This changes the naming of the monitoring action group to reflect the fact that there can only be one per subscription, and ensure that it has its own resource group.
=> Improve monitoring action group naming

aks/application_configuration/README.md, aks/application_configuration/resources.tf, aks/application_configuration/variables.tf
This adds a new argument to the application configuration module allowing it to set some sensible default config variables for Rails applications.
=> Add variables for Rails applications

aks/application/README.md, aks/application/resources.tf, aks/application/variables.tf
This automatically adds StatusCake uptime alerts for web applications from each host name and the probe path.
[Trello Card](https://trello.com/c/mKZJ5KPs/417-add-statuscake-to-terraform-application-module)
=> Add StatusCake alerts

aks/application_configuration/data.tf, aks/application_configuration/variables.tf
In setting up the DQT API on AKS, I created a Key Vault in the incorrect region by mistake. It turns out you cannot move a Key Vault to another region and since we have purge protection enabled I cannot delete the Key Vault and recreate it in the correct region for 3 months.
This change adds an optional variable to enable overriding the default Key Vault name.
=> Allow overriding the Key Vault name

aks/application/README.md, aks/application/resources.tf, aks/application/variables.tf
Reverts DFE-Digital/terraform-modules#33
This doesn't work very well because Terraform tries to construct the `statuscake` provider even if an application isn't using it.
=> Revert "Add StatusCake alerts"

aks/postgres/README.md, aks/postgres/outputs.tf
Similar to the Redis module, the `url` output is in a format that .NET applications cannot use. This adds a .NET compatible connection string to the outputs. Unlike the Redis module, this connection string *is* .NET specific and so I've named it `dotnet_connection_string`.
=> Add a .NET-compatible connection string to Postgres outputs

aks/application/README.md, aks/application/outputs.tf, monitoring/statuscake/README.md, monitoring/statuscake/resources.tf, monitoring/statuscake/terraform.tf, monitoring/statuscake/variables.tf
This adds a module which implements StatusCake uptime checks. It accepts a list of URLs to check and a list of contact groups.
This replaces #33 as we had issues with services not using StatusCake.
=> Add StatusCake monitoring module

EXAMPLE.md, README.md
This adds a document which outlines the basic steps necessary to deploy a Rails application to AKS. It doesn't include the GitHub Actions or Makefile which I think should be documented in a different place.
This is very much a first start, and probably isn't enough for someone on their own to start a new application, but it should help us during the migration and we can iterate it in the future. I also think we should probably pull this out in to its own GitHub repo template in the future.
=> Add a document outlining an example Rails deployment

dns/zones/resources.tf, dns/zones/variables.tf, domains/infrastructure/dns.tf, domains/infrastructure/front_door.tf, domains/infrastructure/variables.tf
tags are set at subscription and resource group levels. They are applied to individual resources automatically so there is no need to specify them.
- Call the module with ref=448-make-domain-tags-optional
- Remove the tags argument
=> [448] Make domain tags optional

aks/application/terraform.tf, aks/application_configuration/terraform.tf, aks/cluster_data/terraform.tf, aks/postgres/terraform.tf, aks/redis/terraform.tf
This ensures that each AKS module specifies the providers it requires, and where to find them. This is not strictly necessary if the root module (the service's Terraform code) already defines these, but it's good practice to put these in the modules as well.
=> Specify required providers

aks/application/README.md, aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
This adds a default probe path for applications, setting it to `/healthcheck`. It can be disabled by setting the `probe_path` variable to `null`.
I've extracted the two commits from #33 which added this that were reverted by accident in #39.
=> Add a default probe path

domains/environment_domains/dns.tf, domains/environment_domains/tfdocs.md, domains/environment_domains/variables.tf
At present if we manage the CNAME for a GOV.UK PaaS application using DNS module and we are setting the parallel environment up for the same environment in AKS for example there might be some down time when we add the domain to the front door configuration. This is because there are various bits of setup required, certificate validation and deployments.
This change allows us to add the environment we are migrating e.g. staging, to the domains list and also to the new list `exclude_cnames` so that all the setup except updating the actual CNAME is completed.
To update the CNAME to finally point the environment to the front door endpoint that is already setup, we just remove it from the `exclude_cnames` list and the list of managed domains we pass to the DNS module.
As well as excluding …
=> Improve Azure DNS controlled AKS migration

monitoring/statuscake/terraform.tf, monitoring/statuscake/tfdocs.md
We need to specify the provider explicitly as Terraform can't guess the name as it's not in the `hashicorp` group. This should fix the following error:
```
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/statuscake: provider registry registry.terraform.io does not
│ have a provider named registry.terraform.io/hashicorp/statuscake
│
│ Did you intend to use statuscakedev/statuscake? If so, you must specify that source address in each module which requires that provider.
│ To see which modules are currently depending on hashicorp/statuscake, run the following command:
│     terraform providers
╵
```
[Trello Card](https://trello.com/c/kKrwyzOE/488-bug-error-failed-to-query-available-provider-packages)
=> Specify StatusCake provider

domains/infrastructure/diagnostics.md, domains/infrastructure/front_door.tf, domains/infrastructure/tfdocs.md, domains/infrastructure/variables.tf
Enable logging for Front Door using the Diagnostics settings 
Create a log analytics workspace 
**Testing** 
- You will require PIM as all the Front Doors are in prod, deploy your own front door or use TSC front door in dev  
- In order to test this set the module source to ```ref=409-front-door-logging```
-  run ```make register domains-infra-apply  ``` (example targets register app)
=> 409 front door logging

aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
It is required for some services to keep the package private temporarily. Kubernetes requires a Github user and token to access it.
Deployed successfully on `calculate-teacher-pay`
=> [493] Pull image from private Github registry

aks/postgres/README.md, aks/postgres/outputs.tf, aks/postgres/tfdocs.md
Add `server_id` output to the postgres module. It can be used to create more resources depending on the database server outside of the module, like new databases.
=> [506] Output postgres server id

aks/postgres/resources.tf
Fixed the bug by adding ignore-changes = tags and optional metric config
By introducing the above the forced terraform update does not report any longer
=> 485-bug-postgres-monitoring

domains/infrastructure/tfdocs.md, domains/infrastructure/variables.tf
The variable was introduced without a default value and it breaks deployments which don't use it. Now defauts to false as it's the previous behaviour.
Before change: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/5764673062/job/15629135387
After change: https://github.com/DFE-Digital/teacher-services-cloud/actions/runs/5783519228/job/15672451667
=> [548] Make azure_enable_monitoring optional

aks/cluster_data/variables.tf
Allow at least one more of our app processes and use use more of the memory
We are maxing out CPU and use little memory:
```
kubectl describe nodes -l agentpool=apps1 | egrep -e '^Name|memory|cpu' | egrep -e 'Name|%'
Name:               aks-apps1-29533562-vmss00006d
cpu                3660m (94%)      4600m (119%)
memory             8283172Ki (29%)  11023396Ki (38%)
Name:               aks-apps1-29533562-vmss00007z
cpu                3560m (92%)   4500m (116%)
memory             3932Mi (14%)  6608Mi (23%)
...
```
On a typical node with 4 cores, we have 3 app processes we deployed, totalling 3000m CPU. And some system processes using around 600m.
Today with request = 1
3 * 1000 = 3000m
rest = 600m
3000 + 600 = 3600m
With request = 800m
3 * 800m = 2400m
rest = 600m
2400 + 600 = 3000m
This …
=> [450] Set production cpu_min to 0.8

aks/cluster_data/README.md, aks/cluster_data/outputs.tf, aks/cluster_data/tfdocs.md, aks/cluster_data/variables.tf
Add new output to cluster_data. Useful output to determine the full web application domain on any cluster
Use module.cluster_data.ingress_domain on an existing deployment
=> [574] cluster_data ingress_domain output

aks/redis/resources.tf
Azure redis creation is very slow at the moment and frequently fails. This should solve most issues as it takes about 30-45min.
=> [633] Increase redis timeout from 30m to 1h

aks/postgres/resources.tf, aks/postgres/tfdocs.md, aks/postgres/variables.tf
Some extensions, in my case `postgis`, do not work on the official Postgres docker image. In order to use it, I introduced a new variable to make the image configurable.
=> Provide docker image for database in kubernetes deployment as variable

domains/environment_domains/dns.tf, domains/environment_domains/front_door.tf, domains/environment_domains/front_door_rules.tf, domains/environment_domains/tfdocs.md, domains/environment_domains/variables.tf
We want to use frontdoor for multiple dns zones with each one having its own apex. Update the apex condition to allow apex, apex<Something>...
Update Frontdoor and Frontdoor rules
=> Allow apex domains from multiple zones

monitoring/statuscake/resources.tf, monitoring/statuscake/tfdocs.md, monitoring/statuscake/variables.tf
We want to be able to detect front door SSL errors using statuscake, but the default 2 confirmations may hide them.
Add a new "confirmation" variable to override it, but keep the default value as 2.
In a repo using statuscake, point terrafile to this branch and test adding confirmation.
Example in teaching-record-system:
```
...
~ resource "statuscake_uptime_check" "main" {
~ confirmation   = 2 -> 0
id             = "6932525"
name           = "https://trs-production-ui.teacherservices.cloud/health"
tags           = []
}
Plan: 0 to add, 3 to change, 0 to destroy.
```
=> [792] Override statuscake confirmations

aks/postgres/resources.tf, aks/postgres/tfdocs.md, aks/postgres/variables.tf, aks/redis/resources.tf, aks/redis/tfdocs.md, aks/redis/variables.tf
Add window_size to postgres snapshot for prod env
=> Add window_size to postgres module

aks/application/variables.tf, aks/application_configuration/variables.tf, aks/postgres/variables.tf, aks/redis/variables.tf, domains/environment_domains/variables.tf, domains/infrastructure/variables.tf, monitoring/statuscake/variables.tf
So we can have the option of leaving some parameters empty and they pick the default value or we override the default other values when we use the modules
Make terraform module variables nullable if they are optional and have default values(and the default value isn't null)
=> Make terraform module variables nullable

dns/Readme.md, dns/zones/resources.tf, dns/zones/tfdocs.md, domains/infrastructure/variables.tf
We need to change the certificate authority as the supplier has changed
Update CAA record from digicert.com to both globalsign.com and digicert.com
=> Update CAA record to globalsign and digicert

aks/cluster_data/variables.tf
https://trello.com/c/UNWoI5f8/885-bug-deployments-are-timing-out-on-the-test-cluster
1 ) Test cluster double the number of pods per node.
2 ) Prod cluster 8 pods per node instead of 5.
cpu_min  changed for both test and prod.
=> CPU min reduced to run more pods on node.

aks/postgres/resources.tf
https://trello.com/c/lbzJQnjY/786-terraform-modules-postgres-log-retentionpolicy-is-deprecated
Removed deprecated retention_policy 
Removed retention_policy in metric
Testing :
1 )   Checkout get-into-teaching-api  , create feature branch and updated development_aks_Terraform file to use feature branch 786-terraform-modules-postgres-log-retentionpolicy-is-deprecated ( https://github.com/DFE-Digital/get-into-teaching-api/pull/1335/files)
2 )  Do terraform plan `make development_aks terraform-plan IMAGE_TAG=master` , There should be no warnings 
`
module.application_configuration.kubernetes_secret.main: Refreshing state... [id=git-development/gitapi-development-0e1809601ee6cca45e993c6d925193302f13d9b1]
module.api_application.kubernetes_deployment.main: Refreshing state... …
=> Removed deprecated retention_policy

aks/cluster_data/README.md, aks/cluster_data/data.tf, aks/cluster_data/outputs.tf, aks/cluster_data/tfdocs.md, aks/cluster_data/variables.tf
Make it easier for apps to deploy to Azure RBAC enabled clusters
Update cluster_data outputs and introduce the spn_authentication variable to choose between spn and azurecli authentication
See draft PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3949
=> [925] Update cluster_data outputs for Azure RBAC

aks/postgres/resources.tf, aks/postgres/tfdocs.md, aks/postgres/variables.tf
Required for migrating Apply for teacher training to terraform-modules without rebuilding the database
Add variable azure_name_override
Run Apply for teacher training terraform from branch 1609-apply-for-tt-migrate-code-to-terraform-modules
=> [1609] Override postgres server name

monitoring/statuscake/resources.tf
We had an incident with a expired certificate and it took us hours to detect it. There was a Statuscake uptime check, but it did not show a problem with the website.
Enable the "validate_ssl" option by default so it alerts when the certificate is expired.
- Run terraform on publish staging for example, using the branch for terrafile
- Observe the ssl setting is enabled
=> [1649] Validate SSL on uptime check

aks/application/README.md, aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
to enable automatically scraping custom metrics
added variables that will enable custom metrics scraping
add scraping to a particular application eg school experience
=> created custom metrics auto scraping 

aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
Add enable_logit option for the aks application module.
Setting to true will enable pod log forwarding for that deployment.
https://trello.com/c/WTWtPR8H/906-spike-application-log-shipping 
application module terraform updates.
New variable enable_logit with default false
Deploy an app using this branch and pass enable_logit with true value
Requires associated teacher-services-cloud PR to have been merged first.
=> Add enable_logit option to application annotations

aks/postgres/tfdocs.md, aks/postgres/variables.tf, aks/redis/tfdocs.md, aks/redis/variables.tf
We're receiving alerts about postgres CPU usage but the team is not concerned when it's only briefly above 60%
Change default thresholds to 80%
Run terraform-plan from a service environment with monitoring enabled
=> [1730] Increase default alert thresholds to 80%

aks/application/resources.tf
If enable_logit is set for an app env, we will send container logs to both logit and azure log analytics
This adds an annotation that will disable the send to azure log analytics when logit is enabled
This will save costs as we won't be storing logs in 2 places
https://trello.com/c/EBBpNMZG/1780-review-log-analytics-cost-savings
Update logit_annotations to include "fluentbit.io/exclude" = "true"
This will only work if log_collection_settings.filter_using_annotations is enabled for k8s ama-logs
Can point a service to this branch, enable_logit and run deploy-plan
and/or check dev cluster6 where this has been enabled for apply_review_rm9
=> Add log analytics containerlog exclude for logit

monitoring/statuscake/resources.tf
When a domain is set up with a redirect, the StatusCake SSL check was following the redirect and got the data of the end website certificate. For instance, https://professional-development-for-teachers-leaders.education.gov.uk/ redirects to https://www.gov.uk/guidance/national-professional-qualification-npq-courses. So the check was on www.gov.uk instead of professional-evelopment-for-teachers-leaders.education.gov.uk.
Remove the follow redirect option
Tested from cpd-information:
```
Terraform will perform the following actions:
~ resource "statuscake_ssl_check" "main" {
~ follow_redirects = true -> false
id               = "320866"
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
=> [1806] Prevent statuscake SSL checks from following redirects

aks/postgres/resources.tf, aks/redis/resources.tf
The message had a hardcoded value but the actual threshold was changed
Make the threshold in the description use the variable
Run deploy-plan from Apply:
```
~ resource "azurerm_monitor_metric_alert" "cpu" {
~ description         = "Action will be triggered when cpu use is greater than 60%" -> "Action will be triggered when cpu use is greater than 80%"
id                  = "/subscriptions/3c033a0c-7a1c-4653-93cb-0f2a9f57a391/resourceGroups/s189p01-att-pd-rg/providers/Microsoft.Insights/metricAlerts/s189p01-att-production-psql-cpu"
name                = "s189p01-att-production-psql-cpu"
tags                = {
"Environment"      = "Prod"
"Product"          = "Apply for postgraduate teacher training"
"Service Offering" = "Apply for postgraduate teacher training"
}
}
~ resource …
```
=> [1815] Fix alert threshold message

aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
The namespaces are being configured with WIF. This allows apps to use it.
Add variable enable_gcp_wif to bind to the service account
Tested and demoed with https://github.com/DFE-Digital/register-trainee-teachers/pull/4325
=> [1762] Enable GCP workload identity federation

aks/application/resources.tf
https://trello.com/c/p9TYi8Rp/1850-decrease-container-liveness-probes
Application deployment Liveness probe settings need tuning
Current setting generates a lot of probe activity and log entries per container. 
Old settings 
- failure_threshold = 10, period_seconds = 1, timeout_seconds = 10
- i.e. 1 probe per second, 10 consecutive failures (9s after first failure) trigger container replacement, 10s timeout
New settings
- failure_threshold = 5, period_seconds = 5, timeout_seconds = 5
- i.e. 1 probe per 5 seconds, 5 consecutive failures (20s after first failure) trigger container replacement, 5s timeout
deploy-plan from a service pointed to this branch
=> Change deployment liveness probe settings

aks/postgres/resources.tf
https://trello.com/c/OPjefUGP/1831-security-ensure-cross-tenant-replication-is-not-enabled
Added default value as false for cross_tenant_replication_enabled
Tested : https://github.com/DFE-Digital/register-trainee-teachers/tree/1831-security-ensure-cross-tenant-replication-is-not-enabled
make pen deploy IMAGE_TAG=48696c5cd836b7ec49b
Storage  resource has been updated : s189t01rttdbbkppensa
=> Cross Tenant Replication disabled

aks/postgres/resources.tf
To prevent accidental or malicious deletion, we need to add soft delete to storage accoun
Add soft delete to [terraform-modules/aks/postgres/resources.tf at main · DFE-Digital/terraform-modules](https://github.com/DFE-Digital/terraform-modules/blob/main/aks/postgres/resources.tf#L108)
i.e. add a delete_retention_policy of 7 days for blobs and containers
=> Add soft delete for storage backup

aks/postgres/resources.tf, aks/postgres/tfdocs.md
Connection throttling added to postgresql config.
Added config connection_throttling = on
Added config connection_throttling = on
QA Terraform plan  for get-a-teacher-relocation-payment: https://github.com/DFE-Digital/get-a-teacher-relocation-payment/pull/427/files
+ resource "azurerm_postgresql_flexible_server_configuration" "connection_throttling" {
+ id        = (known after apply)
+ name      = "connection_throttling"
+ server_id = "/subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourceGroups/s189t01-trp-qa-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/s189t01-trp-qa-pg"
+ value     = "on"
}
=> Connection throttling added to postgresql

aks/application/resources.tf
[](https://trello.com/c/VvUlGlFN/1834-security-disable-automount-of-serviceaccount-token)
Set automount_service_account_token = false for kubernetes_deployment
Access the following link: get-school-experience-review-pr-3.test.teacherservices.cloud
Ensure App deployments are running successfully with the new settings
=> Set automount_service_account_token to false for kubernetes deployment

aks/application/resources.tf
Set the RuntimeDefault seccomp profile as customisation may not be needed at this time.
ITHC recommendations to improve container security
Seccomp stands for secure computing mode. It can be used to sandbox the privileges of a process, restricting the calls it is able to make from userspace into the kernel.
Set seccompt default profile in the application module
Check Register review app: https://register-pr-4416.test.teacherservices.cloud/ ([PR](https://github.com/DFE-Digital/register-trainee-teachers/pull/4416))
=> [1891] Enable RuntimeDefault seccomp profile on containers

aks/postgres/outputs.tf
Removed hard code value of SSL Mode.
SSL Mode Value set based on user_azure. 
Deployed review app using this branch  : https://github.com/DFE-Digital/teaching-record-system/tree/1813-standardise-logging-terraform-module-test.
make dv_review terraform-apply  CLUSTER=cluster2 IMAGE=ghcr.io/dfe-digital/teaching-record-system:b96c149d3b2db5f4ce4ddb29928cfec6af0e286a  APP_NAME=2222
=> SSL mode value set based in use_azure flag

aks/application/resources.tf
Added security context for container
Added security context capabilities for container
Deployed review app on cluster2  it is working with out any issues (https://github.com/DFE-Digital/register-trainee-teachers/tree/1890-security-aks-container-hardening-capabilities-test) 
After deployment , this changes can be verified as below.
` kubectl -n development get po register-2222-5994967dbd-x7mxh -o jsonpath='{.spec.containers[*].securityContext}'
{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false,"seccompProfile":{"type":"RuntimeDefault"}}
`
=> Added capabilities to container security context

aks/postgres/resources.tf, aks/postgres/tfdocs.md, aks/postgres/variables.tf, aks/redis/resources.tf, aks/redis/tfdocs.md, aks/redis/variables.tf
Set frequency based on alert window size
Set  frequency to  azurerm_monitor_metric_alert based on alert window size.
Tested on test branch : https://github.com/DFE-Digital/publish-teacher-training/tree/1927-allow-metric-frequency-override-test.
run terraform plan : make staging_aks deploy-plan IMAGE_TAG=96adb7639cb29bb97616939b88fc3e65aa3485a1.
it showed updating frequency as below for "alert_window_size": "PT1H"
~ frequency           = "PT1M" -> "PT30M"
=> Added alert frequency monitor metric

aks/postgres/resources.tf
Related to issue https://github.com/hashicorp/terraform-provider-azurerm/issues/26098
We must ignore changes to the public_network_access_enabled argument as it becomes enforced from azurerm version v3.105.0.
This will allow us to upgrade azurerm in all the repositories. Then we will be able to set public_network_access_enabled to false and remove this ignore_changes.
Add public_network_access_enabled to ignore_changes lifecycle
See testing in https://hedgedoc.teacherservices.cloud/GfdrzaeGRKGO49k69ANvrQ?edit
=> [1839] Fix ConflictingPublicNetworkAccessAndVirtualNetworkConfiguration

aks/postgres/resources.tf
Related to issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/26098
The property must be set explicitly or it defaults to true. All providers have been updated to be able to use it.
- remove lifecycle to ignore change to public_network_access_enabled
- Explicitly set public_network_access_enabled to false
Test branch 1839-temp on ECF
`make production terraform-plan CONFIRM_PRODUCTION=y DOCKER_IMAGE=ghcr.io/dfe-digital/early-careers-framework:a9ed25957fb1190234e8289c71576611a401833e `
should show no change to postgres
Make sure all providers have been updated
=> [1839] Disable public_network_access_enabled on postgres

aks/application/resources.tf
Background workers may have issues if 2 versions run at the same time. Since they don't receive user traffic, it does not matter if they are stopped while getting replaced.
Use the Recreate deployment strategy when the deployment is not a web app
Deploy https://github.com/DFE-Digital/apply-for-teacher-training/pull/9742 alternatively:
- `make review_aks deploy PR_NUMBER=9742 IMAGE_TAG=daf97fd0483cf5e9e2d885621a209b8f3da703e5`
- `make review_aks deploy PR_NUMBER=9742 IMAGE_TAG=main`
Observe pods:
- `watch -n 1 "kubectl -n bat-qa get pods | grep 9742"`
The web app creates a new one before terminating the initial one. The workers simply terminate and create.
=> [1995] Set deployment stragegy to recreate for non web deployments

monitoring/statuscake/resources.tf, monitoring/statuscake/tfdocs.md, monitoring/statuscake/variables.tf
Claims worker use [delayed jobs](https://github.com/collectiveidea/delayed_job). There is a known issue with it: when there is a database error, it stops processing jobs.
We should monitor it so we know when it's failed.
https://trello.com/c/PQgfB2yQ/1961-claims-worker-heartbeat-monitor
Add a new module for statuscake heartbeat check
=> Add statuscake heartbeat check

aks/postgres/resources.tf
We set the postgres password in the container using a shell environment variable. If the variable contains a sequence of 2 dollar signs `$$`, the actual password may actually have only one `$`. Since the webapp is still configured with `$$`, they don't match and authentication fails.
This commit replaces all sequences of multiple dollar signs with a single one.
Use terraform console:
```
% terraform console
> replace("ab$$cYJH$V&*$$$$£^d","/\\$+/","$")
"ab$cYJH$V&*$£^d"
```
See review app https://github.com/DFE-Digital/itt-mentor-services/pull/985: https://manage-school-placements-985.test.teacherservices.cloud/
=> [860] Fix postgres database password issues with $$

aks/postgres/resources.tf
Pipeline failing in Apply for TT: https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/10684507769/job/29618041006
Sanitise password in both cases: existing password and generated password
Run `make review_aks deploy-plan PR_NUMBER=9791` in Apply for TT
=> [860] Fix postgres when using existing database password

monitoring/statuscake/resources.tf, monitoring/statuscake/tfdocs.md, monitoring/statuscake/variables.tf
We receive alerts for brief downtimes such as https://ukgovernmentdfe.slack.com/archives/C011EM7HU85/p1726012917476049Connect your Slack account
In this case the healthcheck monitors the presence of sidekiq. But sidekiq may be briefly absent when it is redeployed. We should only alert if it remains down for a while.
Add trigger_rate variable so that the value can be set when module is used
https://trello.com/c/8byYzOY9/2040-delay-statuscake-alerts
=> Add delay to statuscake alert

monitoring/statuscake/resources.tf
Each region has multiple StatusCake servers. If it is repeated, the confirmations will use another server in the same region. We want the London region as most of our users are in UK. Focusing on it means we may not alert if a service is down for London but available for another country, as may happen with the front door CDN
Repeat 3 London regions
Check statuscake upptime check created from https://github.com/DFE-Digital/itt-mentor-services/pull/1029
=> [1974] Repeat London as StatusCake region

.github/workflows/lint.yaml, aks/application/resources.tf
Increase security by preventing processes inside the container from opening connections on privileged ports (0-1024).
All applications running on AKS run on unprivileged ports.
- Drop all container capabilities, including NET_BIND_SERVICE
- Pin terraform-docs version to 1.2.2 because of issue: https://github.com/terraform-docs/gh-actions/issues/145
Review app on ITTMS: https://github.com/DFE-Digital/itt-mentor-services/pull/1052
=> [2004] Remove NET_BIND_SERVICE container capability

aks/application/variables.tf, aks/dfe_analytics/README.md, aks/dfe_analytics/authorise_workflow.sh, aks/dfe_analytics/data.tf, aks/dfe_analytics/outputs.tf, aks/dfe_analytics/provider.tf, aks/dfe_analytics/resources.tf, aks/dfe_analytics/tfdocs.md, aks/dfe_analytics/variables.tf
It is not considered good practice to keep the provider definition inside the module
- Remove the provider definition
- Refactor and remove unused variables
- Review IAM roles
See AFQTS PRs:
- reuse dataset: https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2441
- create dataset: https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2457
=> [2041] Remove provider from aks/dfe_analytics

aks/postgres/resources.tf, aks/postgres/tfdocs.md, aks/postgres/variables.tf
It is useful to let the app create the database in some cases, for instance to allow rails db:prepare to work
Make create database optional for azure DB and container DB
See https://github.com/DFE-Digital/schools-experience/pull/3308
=> [2115] Make create database optional

aks/dfe_analytics/resources.tf
When the module is used with existing google resources, the old service accounts remain. It would be helpful to add an explicit description to the new service accounts to identify them correctly.
Add description to service accounts
Tested in https://github.com/DFE-Digital/apply-for-qualified-teacher-status/pull/2493
Check service account in GCP
=> [2130] Add description to Google service account

domains/environment_domains/front_door.tf, domains/environment_domains/front_door_security_rules.tf, domains/environment_domains/tfdocs.md
Add redirect to security domain based on endpoint
Redirect to vdp.security.education.gov.uk if querying "/.well-known/thanks.txt", "/thanks.txt"
Test module against a review app to validate.
Validate redirects are working properly for test deployment on AYTQ for AYTQ and CTR domains
https://test.access-your-teaching-qualifications.education.gov.uk/.well-known/security.txt
https://test.access-your-teaching-qualifications.education.gov.uk/.well-known/thanks.txt
https://test.access-your-teaching-qualifications.education.gov.uk/security.txt
https://test.access-your-teaching-qualifications.education.gov.uk/thanks.txt
**With uppercase -> redirect transform in place on ruleset**
https://test.access-your-teaching-qualifications.education.gov.uk/.well-known/sEcuriTY.txt …
=> Adding redirect rules for security domains

dns/records/tfdocs.md, dns/records/variables.tf, dns/zones/resources.tf, dns/zones/tfdocs.md, dns/zones/variables.tf
It is sometimes required to create TXT records with multiple values for the same record name
Add txt_record_list option
Tested in https://github.com/DFE-Digital/teacher-services-cloud/pull/314
=> [2134] Create DNS zones having multiple values TXT records

aks/dfe_analytics/resources.tf
Avoid clash with the existing service accounts in gcloud.
new service accounts in gcloud need to avoid a clash with the existing service accounts. Hence the name of the service account has been appended.
The name of the service account has been appended.
The name of the service account has been appended. No other change.
=> Update service account name

aks/dfe_analytics/resources.tf
Fix for error in TRS preprod:
```
Error: "account_id" ("appender-wif-trs-pre-production") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"
```
Change the service account name to allow longer environment names
Run terraform plan on https://github.com/DFE-Digital/teaching-record-system/pull/1681
```
+ resource "google_service_account" "appender" {
+ account_id   = "app-wif-trs-pre-production"
+ description  = "Configured with workflow identity federation from Azure"
+ disabled     = false
+ display_name = "Service Account appender to trs in pre-production environment"
...
```
=> [2124] Reduce length of Bigquery service account name

domains/environment_domains/front_door_security_rules.tf
The [url_path_condition doc](https://registry.terraform.io/providers/hashicorp/azurerm/3.116.0/docs/resources/cdn_frontdoor_rule#match_values-14) recommends against it
Remove the leading slash in the matched strings
Tested on Register QA:
https://qa.register-trainee-teachers.service.gov.uk/security.txt
https://qa.register-trainee-teachers.service.gov.uk/.well-known/security.txt
https://qa.register-trainee-teachers.service.gov.uk/.well-known/thanks.txt
https://qa.register-trainee-teachers.service.gov.uk/thanks.txt
=> [2171] Remove leading slash in URL redirect

aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
Required to run container processes with a non-root user
Add run_as_user and run_as_group variables
Test with hedgedoc. See https://github.com/DFE-Digital/teacher-services-hedgedoc/pull/6
Update reference in https://github.com/DFE-Digital/teacher-services-hedgedoc/pull/6
=> [2179] Implement pod run_as_user

aks/postgres/resources.tf, aks/postgres/tfdocs.md, aks/postgres/variables.tf
The default postgres container image had a harcoded version number
Use var.server_version by default
Tested in https://github.com/DFE-Digital/itt-mentor-services/pull/1226
=> [2178] Fix postgres container image version

aks/application_configuration/resources.tf
Fix for error: https://github.com/DFE-Digital/get-into-teaching-app/actions/runs/12253181382/job/34182474422
The current workaround is to provide a non-null value: https://github.com/DFE-Digital/get-into-teaching-app/pull/4417
Ignore the null variable when calculating hash. We use the same behaviour for secrets
Test before applying https://github.com/DFE-Digital/get-into-teaching-app/pull/4417
=> [2182] Allow null value in config map

domains/environment_domains/front_door.tf, domains/environment_domains/tfdocs.md, domains/environment_domains/variables.tf
The name of the custom domain in front door is the same as the subdomain. Subdomain with 1 character is allowed but not the custom domain name.
This is required as the length of "<domain>.<zone>" cannot exceed 64 characters and some subdomains must be 1 character to fit in.
Add a fix to create a longer name when the subdomain is 1 character.
Implemented in https://github.com/DFE-Digital/npq-registration/pull/2070
=> [2183] Allow 1 character custom domains length

aks/cluster_data/README.md, aks/cluster_data/data.tf, aks/cluster_data/outputs.tf, aks/cluster_data/tfdocs.md, aks/cluster_data/variables.tf
Update kubelogin arguments to use OIDC instead of service principal secret
Update kubelogin arguments
See https://github.com/DFE-Digital/itt-mentor-services/pull/1253
Update https://github.com/DFE-Digital/itt-mentor-services/pull/1253 to point at main
=> [2151] Allow github actions OIDC authentication to AKS clusters

aks/cluster_data/data.tf, aks/cluster_data/outputs.tf, aks/cluster_data/tfdocs.md, aks/cluster_data/variables.tf
The logic introduced for OIDC was overly complicated
Depends on https://github.com/DFE-Digital/github-actions/pull/106
Make use of AAD_LOGIN_METHOD environment variable instead of command line arguments
See https://github.com/DFE-Digital/itt-mentor-services/pull/1281
Update references to oidc-ga in https://github.com/DFE-Digital/itt-mentor-services/pull/1281
=> [2151] Simplify kubelogin arguments

aks/postgres/resources.tf, aks/redis/resources.tf
The default node pool is reserved for the system. User apps should be deployed to the apps1 node pool.
Use the node_selector to pin the pods to the application node pool
Used in ITTMS PR: https://github.com/DFE-Digital/itt-mentor-services/pull/1300
Check all pods are deployed to the apps1 node pool:
```
kubectl get pods -A -o wide | grep itt-mentor-services-1300
```
=> [2200] Pin postgres and redis to the application node pool

aks/application_configuration/outputs.tf, aks/application_configuration/tfdocs.md, aks/cluster_data/outputs.tf, aks/secrets/outputs.tf
Application variables may be useful to read in terraform to configure the infrastructure
Create outputs for variables and secrets
- `terraform -chdir=aks/application_configuration init `
- `terraform -chdir=aks/application_configuration validate`
=> [2203] Output application configuration variables

domains/environment_domains/rate_limit.tf, domains/environment_domains/tfdocs.md, domains/environment_domains/variables.tf
Create a rate limit per environment to prevent from denial of service attacks
Introduce the rate_limit variable in the environment_domains module to create a firewall policy with a rate limit custom rule
Implemented in branch 2214-front-door-rate-limiting of https://github.com/DFE-Digital/teacher-pay-calculator/
Applied to front door s189p01-ctp-domains-fd
You can test with Azure load testing: s189p01-ctp-lt
=> [2214] Front door rate limiting

domains/environment_domains/locals.tf, domains/environment_domains/rate_limit.tf
Adding rate limit firewall policy resources for environment domains fail if multiple zones are in the same service.
This is due to trying to create multiple policies with the same name.
Add a short prefix based on the first 3 letters of the zone and use this is the firewall policy name
deploy plan against this branch
Have run this from git, afqts and aytq.
=> fix rate limit for multiple zones

domains/environment_domains/locals.tf
Current firewall policy name doesn't guarantee uniqueness with our existing front door config.
Alter the prefix to ensure name will be unique within the same resource group
make production domain-plan against this branch from ittms
=> Fix to ensure firewall policy name is unique

aks/application/resources.tf, aks/application/tfdocs.md, aks/application/variables.tf
- Add run_as_non_root variable to enforce non-root user execution
- Update security_context in kubernetes_deployment to include run_as_non_root setting
- Update terraform-docs generated documentation
- Enhances container security by allowing enforcement of non-root execution at Kubernetes level
- Supports ITHC security recommendations for container hardening
=> Add support for non-root in application module
