DFE-Digital/terraform-modules

domains/environment_domains/front_door.tf
domains/environment_domains/variables.tf

Terraform support for Azure front door custom domain is now available. This commit adds the missing FD reources as part of custom domain deployment.

Add custom domain and route

---

domains/environment_domains/front_door.tf
domains/environment_domains/variables.tf
domains/infrastructure/dns.tf

Let front door cache URLs by path
Cache a list of path patterns for all domains in this environment
Test with apply branch `88-investigate-apply-frontdoor-caching`

[88] Frontdoor caching

---

.github/workflows/lint.yaml
.tool-versions
domains/environment_domains/variables.tf

This adds some automated testing of the code using the built in `terraform fmt` command with a GitHub Action workflow.

Add linting checks

---

README.md
aks/redis/README.md
aks/redis/data.tf
aks/redis/output.tf
aks/redis/resources.tf
aks/redis/variables.tf

This adds a new module which deploys a Redis instance, either on Azure or via Kubernetes.

Add AKS Redis module

---

README.md
aks/application_configuration/README.md
aks/application_configuration/data.tf
aks/application_configuration/outputs.tf
aks/application_configuration/resources.tf
aks/application_configuration/variables.tf

This adds a new module which generates the application configuration necessary to deploy the application to Kubernetes. This includes both a configuration map and the secrets.

Add AKS Application Configuration module

---

README.md
aks/postgres/README.md
aks/postgres/data.tf
aks/postgres/outputs.tf
aks/postgres/resources.tf
aks/postgres/variables.tf

This adds a new module which deploys a PostgreSQL instance, either on Azure or via Kubernetes.

Add AKS PostgreSQL module

---

README.md
aks/application/tfdocs.md
aks/application_configuration/tfdocs.md
aks/cluster_data/tfdocs.md
aks/postgres/tfdocs.md
aks/redis/tfdocs.md
aks/secrets/tfdocs.md
dns/records/tfdocs.md
domains/environment_domains/tfdocs.md
domains/infrastructure/tfdocs.md
monitoring/statuscake/tfdocs.md

Add command to generate terraform-doc's in readme, and generate them for all present modules.

Add Terraform docs

---

aks/postgres/data.tf
aks/postgres/resources.tf
aks/postgres/variables.tf

Module additions to include resource deployment of Log Analytics Workspace specific to Postgres. The resources have a dependency on Azure Backing services to be enabled

Enable Log Analytics for Postgres

---

aks/postgres/data.tf
aks/postgres/resources.tf

Removed a condition and added some white space per resource to bring it in line.

Remove condition

---

README.md

The code block is missing a closing three backticks.

Add missing closing block

---

.github/workflows/lint.yaml
.terraform-docs.yaml
README.md
aks/application/tfdocs.md
aks/application_configuration/tfdocs.md
aks/cluster_data/tfdocs.md
aks/postgres/tfdocs.md
aks/redis/tfdocs.md
dns/zones/tfdocs.md
domains/infrastructure/tfdocs.md

This improves Terraform Docs to configure a workflow which checks they are always up to date.

Add workflow for Terraform Docs

---

aks/redis/resources.tf
aks/redis/variables.tf

Add multiple AZ's to make the redis cache service more resilient

Module addition for multiple AZ

---

aks/postgres/resources.tf

Fix permissions for the db backup storage account when it is created
https://trello.com/c/GDDsSdlZ/791-security-fix-backup-storage-account-permissions
Update the backup resource terraform definition
Tested in register
You can point to this branch from any service using a bkp sa and run deploy-plan

Update bkp sa permissions

---

aks/application/variables.tf

bug fix to remove nullable from module probe_path
remove nullable=false in variables
resolves healthcheck issue

removed nullable from probe_path

---

README.md

There is still some confusion around the process
Update the content to make it clearer
Review README

[1816] Update release process documentation

---

aks/application/resources.tf

ITHC recommendation: prevent user inside the container from elevating privileges
set `allow_privilege_escalation = false`
Check review app at https://register-pr-4416.test.teacherservices.cloud/

[1832] Disallow privilege escalation

---

aks/postgres/tfdocs.md
aks/postgres/variables.tf

We need to update postgres version to the latest stable one
Change postgres version to 16
https://trello.com/c/4PBO6Miu/834-change-default-postgres-version-to-16

Postgres 16 changes

---

aks/dfe_analytics/README.md

Missing manual step when migrating to dfe_analytics module
Update dfe_analytics README
Read documentation

Update dfe_analytics doc with service account delete

---

aks/application/README.md
aks/application_configuration/README.md
aks/cluster_data/README.md
aks/dfe_analytics/README.md
aks/postgres/README.md
aks/redis/README.md
aks/secrets/README.md
dns/records/readme.md
dns/zones/readme.md
domains/environment_domains/README.md
domains/infrastructure/README.md

Improve modules documentation
- Clarify dfe analytics documentation
- Add missing READMEs
- Add tfdocs link to READMEs
Review documentation

[2142] Update dfe_analytics README

---

README.md
aks/job_configuration/README.md
aks/job_configuration/resources.tf
aks/job_configuration/tfdocs.md
aks/job_configuration/variables.tf

##Context: Creation of K8S Job Module for apps teams

1976-add-migration-job-to-terraform-modules

---

aks/job_configuration/resources.tf
aks/job_configuration/tfdocs.md
aks/job_configuration/variables.tf

Minor changes for aks job module
- change resource name from migration to main
- allow override of max memory with default 1Gi
test against branch

Minor aks job module updates
